
query Restaurant($where: RestaurantWhereUniqueInput!) {
  restaurant(where: $where) {
    id
    name
    description
    location {
      lat
      lng
    }
    owner {
      id
      name
      nickname
      isAdmin
      phone
      email
      role
    }
    reservationPrice
    info
    category
    images {
      id
      name
      description
      image {
        id
        filesize
        width
        height
        extension
        url
      }
    }
    imagesCount
    reviews {
      id
      imagesCount
      timestamp
      edited
      title
      content
      likes
    }
    reviewsCount
  }
}
